### ISSUE TITLE
Soundpad CANNOT play the installed music

### ISSUE THREAD

**Issue by Warrel1087** [L-uu/MusicToSoundpad#3]
The cmd installs the audio/song as a .webm and soundpad cannot play it (img below)
![image](https://github.com/L-uu/MusicToSoundpad/assets/135077447/4d9f306c-edc3-4fbb-b2a9-ef4deea63228)

How to fix this?

**Comment by L-uu** [comment]
Hi, did you download the zip package or just the exe from the releases tab? Ffmpeg is required to extract the audio into the mp3 format and it comes bundled in the zip package.
